import drGopiImg from "@/assets/dr-gopi-krishna.png";

export const CLINIC = {
  name: "Venkateswara Multi Speciality Dental Clinic",
  shortName: "Venkateswara Dental Clinic",
  tagline: "Award-Winning Dental Care & Multi-Speciality Clinic in Balanagar",
  address:
    "Hno 36, Opposite Hotel Samrat Lane, Balanagar Main Rd, behind Gaurav Super Market, Ferozguda, Hyderabad, Telangana 500042",
  area: "Balanagar, Ferozguda, Hyderabad",
  phone: "077991 04626",
  phoneRaw: "07799104626",
  email: "care@venkateswaradentalclinic.in",
  consultationFee: "₹300",
  googleRating: 4.6,
  googleReviewsCount: 624,
  practoRating: "97%",
  practoVotes: 653,
  patientStoriesCount: 653,
  experienceYears: 26,
  hours: [
    { day: "Monday", morning: "09:30 AM – 01:30 PM", evening: "05:00 PM – 08:00 PM" },
    { day: "Tuesday", morning: "09:30 AM – 01:30 PM", evening: "05:00 PM – 08:00 PM" },
    { day: "Wednesday", morning: "09:30 AM – 01:30 PM", evening: "05:00 PM – 08:00 PM" },
    { day: "Thursday", morning: "09:30 AM – 01:30 PM", evening: "05:00 PM – 08:00 PM" },
    { day: "Friday", morning: "09:30 AM – 01:30 PM", evening: "05:00 PM – 08:00 PM" },
    { day: "Saturday", morning: "09:30 AM – 01:30 PM", evening: "05:00 PM – 08:00 PM" },
    { day: "Sunday", morning: "Closed", evening: "By Appointment Only" },
  ],
  summaryStatement:
    "Our clinic is centrally located at Balanagar in Hyderabad. Venkateswara Multi Specialty Dental Hospital offers general and multi-specialty practices, bringing you a full spectrum of dental services and treatments such as Cosmetic Dentistry, Restorative Dentistry, Prosthodontics, Implant Dentistry, Endodontics, Orthodontics, Pediatric Dentistry, Periodontics, Oral & Maxillofacial Surgery and Preventive Dentistry.",
  mapsDirections:
    "https://www.google.com/maps/dir/?api=1&destination=Venkateswara+Multi+Speciality+Dental+Clinic+Balanagar+Hyderabad",
  mapEmbed:
    "https://www.google.com/maps?q=Venkateswara+Multi+Speciality+Dental+Clinic+Hno+36+Balanagar+Hyderabad&t=&z=16&ie=UTF8&iwloc=&output=embed",
};

export const DOCTORS = [
  {
    name: "Dr. Gopi Krishna",
    title: "BDS, MDS - Prosthodontist And Crown Bridge",
    specialty: "Prosthodontist & Crown Bridge Specialist",
    experience: "26 years experience overall",
    rating: "97%",
    votes: 653,
    stories: 653,
    fee: "₹300",
    badge: "Award Winning Doctor in Twin Cities",
    img: drGopiImg,
    bio: "Dr. Gopi Krishna is an Award-Winning Prosthodontist with over 26 years of distinguished clinical experience in the twin cities. Renowned for his non-commercial philosophy, patient empathy, and high-precision dental treatments including Painless Root Canal Treatment (RCT), Ceramic Crowns, Dental Implants, and Dentures.",
    highlights: [
      "26+ Years Clinical Excellence",
      "Award-Winning Specialist in Twin Cities",
      "Non-Commercial & Patient-Centric Care",
      "Expert in Rotary RCT & Fixed Dentures",
    ],
  },
  {
    name: "Dr. Vinay",
    title: "BDS - Dental Surgeon & Restorative Specialist",
    specialty: "General & Restorative Dentist",
    experience: "12+ years experience",
    rating: "98%",
    votes: 420,
    stories: 380,
    fee: "₹300",
    badge: "Patient Recommended Dentist",
    img: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=1000&q=80",
    bio: "Dr. Vinay is widely appreciated for his comforting chairside manner, friendly atmosphere, and gentle handling of complex tooth extractions, pain relief, dental fillings, and preventive care.",
    highlights: [
      "Warm & Welcoming Hospitality",
      "Painless Tooth Extractions & Fillings",
      "Patient-Friendly Dental Guidance",
    ],
  },
];

export const ALL_SURGERIES_TREATMENTS = [
  {
    name: "Root Canal Treatment (RCT)",
    category: "Endodontics",
    desc: "Single & multi-visit rotary endodontic root canal treatments designed for maximum comfort and natural tooth saving.",
    badge: "Most Popular",
    icon: "Stethoscope",
  },
  {
    name: "Rotary R.C.T",
    category: "Endodontics",
    desc: "Advanced motorized rotary endodontic therapy ensuring fast, precision-guided, and painless root canal cleaning.",
    badge: "Advanced Tech",
    icon: "Zap",
  },
  {
    name: "Dental Implants",
    category: "Prosthodontics",
    desc: "Permanent titanium implant posts and realistic crowns restoring full bite function and smile aesthetics.",
    badge: "Specialist",
    icon: "Shield",
  },
  {
    name: "All Types of Ceramic Crowns",
    category: "Prosthodontics",
    desc: "Zirconia, E-max, and full ceramic metal-free crowns providing seamless tooth color matching and durability.",
    badge: "Premium Aesthetic",
    icon: "Sparkles",
  },
  {
    name: "Crowns and Bridges Fixing",
    category: "Prosthodontics",
    desc: "Fixed partial prosthetics and crown cementation to replace missing teeth and reinforce weak teeth structures.",
    badge: "Restorative",
    icon: "CheckCircle",
  },
  {
    name: "Complete & Partial Dentures Fixing",
    category: "Prosthodontics",
    desc: "Custom full set acrylic & flexible partial dentures engineered for optimum comfort, speech, and chewing efficiency.",
    badge: "Comfort Fit",
    icon: "Heart",
  },
  {
    name: "Acrylic Partial Denture",
    category: "Prosthodontics",
    desc: "Cost-effective and lightweight acrylic tooth replacements for single or multiple missing teeth.",
    badge: "Budget Friendly",
    icon: "Smile",
  },
  {
    name: "Cast Partial Denture",
    category: "Prosthodontics",
    desc: "Metallic alloy framework partial dentures providing ultra-strong support, minimal coverage, and long longevity.",
    badge: "Durable",
    icon: "ShieldCheck",
  },
  {
    name: "Tooth Extraction",
    category: "Oral Surgery",
    desc: "Gentle and sterile removal of severely damaged, broken, or unsavable teeth under painless local anesthesia.",
    badge: "Painless",
    icon: "Activity",
  },
  {
    name: "Impaction / Impacted Tooth Extraction",
    category: "Oral Surgery",
    desc: "Surgical wisdom tooth extractions for painful or misaligned impacted molars with quick recovery protocols.",
    badge: "Surgical Specialist",
    icon: "Crosshair",
  },
  {
    name: "Braces and Aligners",
    category: "Orthodontics",
    desc: "Comprehensive teeth straightening with traditional metal/ceramic braces and clear invisible aligner trays.",
    badge: "Smile Alignment",
    icon: "Layers",
  },
  {
    name: "Laser Dentistry",
    category: "Laser Care",
    desc: "Minimally invasive diode laser treatments for bloodless gum contouring, depigmentation, and rapid tissue healing.",
    badge: "High Precision",
    icon: "Sun",
  },
  {
    name: "Tooth Whitening Treatment",
    category: "Cosmetic Dentistry",
    desc: "Professional in-clinic teeth bleaching and stain removal delivering up to 8 shades brighter smile in 45 minutes.",
    badge: "Instant Glow",
    icon: "Sparkle",
  },
  {
    name: "Scaling & Polishing",
    category: "Preventive",
    desc: "Ultrasonic tartar removal, plaque cleaning, and enamel polishing to protect gums and eliminate bad breath.",
    badge: "Essential Care",
    icon: "Feather",
  },
  {
    name: "Dental Fillings",
    category: "Restorative",
    desc: "Aesthetic tooth-colored composite resin fillings to repair cavities seamlessly without visible metal marks.",
    badge: "Non-Commercial",
    icon: "Edit3",
  },
  {
    name: "Dental X-Ray & Diagnostics",
    category: "Diagnostics",
    desc: "High-resolution digital RVG dental X-rays for instant, low-radiation diagnosis of root structures and jawbone density.",
    badge: "Instant Imaging",
    icon: "Camera",
  },
  {
    name: "Cosmetic Dentistry",
    category: "Specialty Practice",
    desc: "Veneers, teeth reshaping, composite bonding, and comprehensive smile makeovers tailored to your face aesthetics.",
    badge: "Design",
    icon: "Eye",
  },
  {
    name: "Restorative Dentistry",
    category: "Specialty Practice",
    desc: "Complete oral rehabilitation, structural tooth repairs, and functional bite alignment.",
    badge: "Core Service",
    icon: "Tool",
  },
  {
    name: "Prosthodontics",
    category: "Specialty Practice",
    desc: "Expert prosthetics care managed directly by Dr. Gopi Krishna (MDS Prosthodontist with 26+ years experience).",
    badge: "Lead Specialty",
    icon: "Award",
  },
  {
    name: "Endodontics",
    category: "Specialty Practice",
    desc: "Root canal therapy, endodontic retreatment, and vital pulp therapy for severe toothache relief.",
    badge: "Pain Relief",
    icon: "Zap",
  },
  {
    name: "Orthodontics",
    category: "Specialty Practice",
    desc: "Correction of overbites, underbites, crowding, and gaps for children, teens, and adults.",
    badge: "Alignment",
    icon: "Compass",
  },
  {
    name: "Pediatric Dentistry",
    category: "Specialty Practice",
    desc: "Friendly, gentle dental checkups, habit breakers, and preventive sealants designed specially for children.",
    badge: "Child Friendly",
    icon: "Smile",
  },
  {
    name: "Periodontics",
    category: "Specialty Practice",
    desc: "Treatment of pyorrhea, bleeding gums, gum recession, deep root planing, and bone grafting.",
    badge: "Gum Health",
    icon: "Shield",
  },
  {
    name: "Oral & Maxillofacial Surgery",
    category: "Specialty Practice",
    desc: "Advanced surgical management of jaw trauma, cyst removals, and complex oral surgical procedures.",
    badge: "Surgical Unit",
    icon: "Crosshair",
  },
  {
    name: "Preventive Dentistry",
    category: "Specialty Practice",
    desc: "Fluoride applications, pit & fissure sealants, and personalized oral hygiene guidance for long-term health.",
    badge: "Wellness",
    icon: "Heart",
  },
  {
    name: "Diagnostic Centres",
    category: "Diagnostics",
    desc: "In-house clinical diagnostic evaluations and digital dental imaging.",
    badge: "In-House",
    icon: "Grid",
  },
  {
    name: "PIVD (Prolapsed Intervertebral Disc) Support",
    category: "Allied Care",
    desc: "Ergonomic, tension-free patient positioning and comfortable treatment chairs suited for spine & PIVD sufferers.",
    badge: "Patient Comfort",
    icon: "UserCheck",
  },
  {
    name: "Diseases in Pregnancy Dental Care",
    category: "Special Care",
    desc: "Safe, specialized trimester-specific dental consultations and emergency care for expectant mothers.",
    badge: "Safe Care",
    icon: "ShieldAlert",
  },
  {
    name: "Blood Test Home Visit",
    category: "Diagnostics",
    desc: "Convenient home sample collection for routine pre-surgical blood tests and general health screening.",
    badge: "At Home",
    icon: "Home",
  },
];

export const PATIENT_STORIES = [
  {
    id: "story-1",
    author: "Mr Bapuji Bolla",
    verified: true,
    timeAgo: "5 years ago",
    treatment: "RCT - Root Canal Treatment",
    doctorName: "Dr. Gopi Krishna (Prosthodontist)",
    rating: 5,
    happyWith: ["Doctor friendliness", "Explanation of the health issue", "Treatment satisfaction"],
    text: "I heard about the great gesture and treatment from my parents earlier, yet experienced live when I visited for my tooth issue recently. I could truly say that he is an Award Winning doctor in the twin cities; not less than globally admirable professional service he has provided. Really happy for his kindness and best to-go-dentist have ever seen. Love the empathy and willingness to serve for my well-being. Thanks a lot for your care and would recommend and refer my near and dear. Happy meeting you, stay healthy! Regards Pavan Kumar Bolla",
    doctorReply: "Thank u",
    doctorReplyDate: "Doctor reply",
  },
  {
    id: "story-2",
    author: "Y Rajitha",
    verified: true,
    timeAgo: "4 years ago",
    treatment: "Dental Fillings & Tooth Pain",
    doctorName: "Dr. Gopi Krishna & Dr. Vinay",
    rating: 5,
    happyWith: [
      "Doctor friendliness",
      "Explanation of the health issue",
      "Treatment satisfaction",
      "Value for money",
    ],
    text: "Both doctors Dr. Vinay and Dr. Gopi krishan are ver welcoming and friendly. The dentist was very nice and information. He made me feel right at home and as if I was a friend. I came in with extremely painful tooth and jaw and never felt any pain or discomfort during the procedure. Both doctors are so patience towards me while doing the whole process. Dr. Vinay provided excellent service and i will be coming here for all my future dental needs! Thank you so much for smooth treatment. I must recommend venkateshwara multi-speciality dental clinic without any second thought. Just go for it👍👍👍👍",
    doctorReply: "Thank u rajitha",
    doctorReplyDate: "Doctor reply",
  },
  {
    id: "story-3",
    author: "Varun Gampa",
    verified: true,
    timeAgo: "2 years ago",
    treatment: "RCT - Root Canal Treatment & Dental Fillings",
    doctorName: "Dr. Gopi Krishna (Prosthodontist)",
    rating: 5,
    happyWith: ["Explanation of the health issue", "Doctor friendliness", "Value for money"],
    text: "Dr Gopi is one gem of a doctor. He explains in detail about the problem and solves it with minimal treatment. He is non-commercial. Unlike other dentists who do fillings irrespective it is required or not, Gopi sir does it only if it is compulsory required. There is little wait time, so better book your appointments in advance.",
    doctorReply: "Thank u",
    doctorReplyDate: "Doctor reply",
  },
  {
    id: "story-4",
    author: "R.Sneha Priya",
    verified: true,
    timeAgo: "5 years ago",
    treatment: "RCT - Root Canal Treatment",
    doctorName: "Dr. Gopi Krishna (Prosthodontist)",
    rating: 5,
    happyWith: ["Doctor friendliness", "Flexible Scheduling", "Sanitation Precautions"],
    text: "Doctor is very professional and diligent in treating dental issues. I personally felt that he interacts well with patients and invests his time which we don't experience from all Doctors these days. I made a few visits and all times he made sure that appointment was according to my schedule as I'm preparing for my exams. Staff are taking all kind of precautions necessary in this covid situation. Value for money👍",
    doctorReply: "Thank u",
    doctorReplyDate: "Doctor reply",
  },
  {
    id: "story-5",
    author: "Mohammed Zaheer Ahmed",
    verified: true,
    timeAgo: "2 years ago",
    treatment: "RCT - Root Canal Treatment",
    doctorName: "Dr. Gopi Krishna (Prosthodontist)",
    rating: 5,
    happyWith: [
      "Doctor friendliness",
      "Explanation of the health issue",
      "Treatment satisfaction",
      "Value for money",
      "Wait time",
    ],
    text: "First time met with Doctor. I liked very much his hospitality, explanation of my treatment, disease reasons, facts what happened and what is required. Very importantly, highly reasonable charges, good methodology of treatment procedure. I strongly recommending to the dental issues sufferers, get the appointment and visit to him. Charges are reasonable comparatively others and Quality treatment upto the satisfactory. ENGR MOHAMMED ZAHEER AHMED- IES",
    doctorReply: "Thank u sir",
    doctorReplyDate: "Doctor reply",
  },
  {
    id: "story-6",
    author: "Shakir Ali",
    verified: true,
    timeAgo: "2 years ago",
    treatment: "General Dentistry & Consultation",
    doctorName: "Dr. Gopi Krishna (Prosthodontist)",
    rating: 5,
    happyWith: [
      "Doctor friendliness",
      "Explanation of the health issue",
      "Treatment satisfaction",
      "Value for money",
      "Wait time",
    ],
    text: "The doctor is fantastic – friendly, explained things clearly. He took the time to explain things well and made me feel comfortable. I left feeling like they really cared about my health. I highly recommend him for a positive and caring healthcare experience.",
    doctorReply: "Thank u",
    doctorReplyDate: "Doctor reply",
  },
  {
    id: "story-7",
    author: "S Srinivas",
    verified: true,
    timeAgo: "5 years ago",
    treatment: "RCT - Root Canal Treatment",
    doctorName: "Dr. Gopi Krishna (Prosthodontist)",
    rating: 5,
    happyWith: ["Doctor friendliness", "Treatment satisfaction", "Value for money"],
    text: "Very polite with patience listens our problems and cures 100% recommend to my friends and relatives",
    doctorReply: "Thank u",
    doctorReplyDate: "Doctor reply",
  },
  {
    id: "story-8",
    author: "R.Aparna",
    verified: true,
    timeAgo: "2 years ago",
    treatment: "Fixed Partial Denture (FPD)",
    doctorName: "Dr. Gopi Krishna (Prosthodontist)",
    rating: 5,
    happyWith: ["Doctor friendliness", "Quality of Prosthetic Treatment"],
    text: "Doctor's treatment was exllent he is so cool and friendly with patients I'm from shaikpet it's so far for me but I'll go for his better treatment.im happy with his staff response.",
    doctorReply: "thank u madam",
    doctorReplyDate: "Doctor reply",
  },
  {
    id: "story-9",
    author: "Rathna Kishor",
    verified: true,
    timeAgo: "5 years ago",
    treatment: "RCT - Root Canal Treatment",
    doctorName: "Dr. Gopi Krishna (Prosthodontist)",
    rating: 5,
    happyWith: [
      "Doctor friendliness",
      "Explanation of the health issue",
      "Treatment satisfaction",
      "Value for money",
    ],
    text: "The experience was so good, the way of explaining was quite amazing, for sure this is the recommend clinic",
    doctorReply: "Thank u",
    doctorReplyDate: "Doctor reply",
  },
  {
    id: "story-10",
    author: "N.Bhagya Rani",
    verified: true,
    timeAgo: "4 years ago",
    treatment: "Dental Fillings",
    doctorName: "Dr. Gopi Krishna (Prosthodontist)",
    rating: 5,
    happyWith: [
      "Doctor friendliness",
      "Explanation of the health issue",
      "Treatment satisfaction",
      "Value for money",
    ],
    text: "Definitely will suggest in case if any one is facing the same issue. Hospitality is also excellent.",
    doctorReply: "Thank u",
    doctorReplyDate: "Doctor reply",
  },
];

export const GOOGLE_REVIEWS = [
  {
    author: "Pavan Kumar",
    text: "I strongly recommend this doctor for any tooth related issues.",
    rating: 5,
    time: "Google Review",
  },
  {
    author: "Jatoth Kamala",
    text: "From the moment I walked in, the atmosphere was calm and professional.",
    rating: 5,
    time: "Google Review",
  },
  {
    author: "Hari Krishna",
    text: "Best place for tooth care",
    rating: 5,
    time: "Google Review",
  },
];

export const GALLERY_IMAGES = [
  {
    src: drGopiImg,
    cat: "Doctors",
    title: "Dr. Gopi Krishna (BDS, MDS)",
    desc: "Chief Prosthodontist & Crown Bridge Specialist",
  },
  {
    src: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1400&q=80",
    cat: "Clinic Operatory",
    title: "Advanced Dental Suite",
    desc: "Ultra-hygienic dental operatory at Balanagar clinic",
  },
  {
    src: "https://images.unsplash.com/photo-1609840114035-3c981b782dfe?auto=format&fit=crop&w=1400&q=80",
    cat: "Treatments",
    title: "Rotary RCT & Diagnostics",
    desc: "Precision digital tools for painless root canal therapy",
  },
  {
    src: "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=1400&q=80",
    cat: "Treatments",
    title: "Dental Implants & Crowns",
    desc: "State of the art dental ceramic prosthetic restoration",
  },
  {
    src: "https://images.unsplash.com/photo-1581585093487-7a909a76b09b?auto=format&fit=crop&w=1400&q=80",
    cat: "Treatments",
    title: "Prosthodontic Dentures",
    desc: "Fixed partial dentures and flexible acrylic/cast dentures",
  },
  {
    src: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=1400&q=80",
    cat: "Doctors",
    title: "Dr. Vinay",
    desc: "Dental Surgeon & Restorative Specialist",
  },
  {
    src: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=1400&q=80",
    cat: "Clinic Exterior",
    title: "Balanagar Main Road Clinic",
    desc: "Convenient location opposite Hotel Samrat Lane",
  },
  {
    src: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?auto=format&fit=crop&w=1400&q=80",
    cat: "Cosmetic Care",
    title: "Teeth Whitening",
    desc: "Laser dental whitening and aesthetic enamel polishing",
  },
];

export const BEFORE_AFTER = [
  {
    before:
      "https://images.unsplash.com/photo-1612277795421-9bc7706a4a34?auto=format&fit=crop&w=1400&q=80",
    after:
      "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?auto=format&fit=crop&w=1400&q=80",
    label: "Teeth Whitening & Smile Design",
  },
  {
    before:
      "https://images.unsplash.com/photo-1571772996211-2f02c9727629?auto=format&fit=crop&w=1400&q=80",
    after:
      "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=1400&q=80",
    label: "Dental Implants & Ceramic Restoration",
  },
];

export function isOpenNow() {
  const now = new Date();
  const day = now.getDay();
  if (day === 0) return false; // Sunday
  const mins = now.getHours() * 60 + now.getMinutes();
  const morningOpen = 9 * 60 + 30; // 09:30
  const morningClose = 13 * 60 + 30; // 13:30
  const eveningOpen = 17 * 60; // 17:00
  const eveningClose = 20 * 60; // 20:00

  return (mins >= morningOpen && mins <= morningClose) || (mins >= eveningOpen && mins <= eveningClose);
}
